version: '3.8'
services:
  db:
    image: mysql
    container_name: mysql-lightit
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: challenge
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "5678:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-lightit
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=challenge
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_data:
